# Generated by Django 5.2 on 2025-06-04 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_notetag_tag_notetag_tag'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notetag',
            unique_together={('note', 'tag')},
        ),
    ]
